# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 092dfc7fc8ca599818badddc84b76c655b87e7f692fe930ab736bd96c30f37fa6470cf7324d0d981ce7e310c3afc0635dd185fe847cf482d9353ba369c9d132d

test:
  secret_key_base: 7f8a348f84e2329b8e17c0bd1cdc787551d918fcba2e1da7cb464a55f1bb80969dbe4286b244f6ab7dacc05decae559c596e05a1113c605182aa3b95edad485e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
